version: "3.8" 
services:
  mongodb:
    image: mongo
    volumes:
      - mongodbdata:/data/db
    env_file: .env
    ports:
      - "${MONGO_INITDB_PORT}:27017"
    container_name: mongodb
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./backend/src:/app/src
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - ./env/backend.env
  #   depends_on:
  #     - mongodb
  #   container_name: azbackend
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend/src:/app/src
  #   ports:
  #     - 3000:3000
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - backend

volumes:
  mongodbdata: 